### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by IbrahimSerhat** [emreycolakoglu/node-tckimlik#1]
Access to fetch at 'https://tckimlik.nvi.gov.tr/Service/KPSPublicV2.asmx?wsdl' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by emreycolakoglu** [comment]
This is related to your development environment setup rather than this package. You shouldn't make AJAX requests to a SOAP api.

Closing as off-topic
